/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppContainer: typeof import('./../components/AppContainer.vue')['default']
    AppH2: typeof import('./../components/AppH2.vue')['default']
    AppLink: typeof import('./../components/AppLink.vue')['default']
    AppPre: typeof import('./../components/AppPre.vue')['default']
    AppPrimaryButton: typeof import('./../components/AppPrimaryButton.vue')['default']
    AppRoundedBorder: typeof import('./../components/AppRoundedBorder.vue')['default']
    PageFormkit: typeof import('./../components/PageFormkit.vue')['default']
    PageGql: typeof import('./../components/PageGql.vue')['default']
    PageIndex: typeof import('./../components/PageIndex.vue')['default']
    PageSignIn: typeof import('./../components/PageSignIn.vue')['default']
    PageVueUse: typeof import('./../components/PageVueUse.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleTimer: typeof import('./../components/SimpleTimer.vue')['default']
    Timer: typeof import('./../components/Timer.vue')['default']
  }
}
